### ISSUE TITLE
Modifications to https://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/documentation-wiki#159]
@Jegelewicz  Can you change the description of the WoRMS (via Arctos) source?  The description was accurate when we first added WoRMS (via Arctos), but now that we have dynamic sources, there is no reason for any entries but those that come from WoRMS with an aphiaID.

Currently it reads: 

WoRMS (via Arctos) | Data primarily from http://www.marinespecies.org/. Some "local" data (eg, names not in WoRMS) may exist. Classifications with aphiaid will be automatically maintained
-- | --

Proposed:
WoRMS (via Arctos) | Data from http://www.marinespecies.org/.  All entries should have a WoRMS aphiaID and will be automatically maintained by the World Register of Marine Species.  

Perhaps it would be good to add a column that shows which sources are internally or externally managed.

By the way, on my "to do" list is a complete revision of How To Create Taxa in Externally Managed Sources which is now unnecessary and misleading.

**Comment by Jegelewicz** [comment]
> Proposed:
> WoRMS (via Arctos) | Data from http://www.marinespecies.org/. All entries should have a WoRMS aphiaID and will be automatically maintained by the World Register of Marine Species.

Done.

> Perhaps it would be good to add a column that shows which sources are internally or externally managed.

I think this is a good idea and goes back to the "managed by" as the number of sources starts to grow, I think that designating how and by whom the source is managed make sense, but should we just do this in the description or make it more explicit?

**Comment by dustymc** [comment]
>managed by

I'm still not seeing any reason for that to exist in the current model.

>should we just do this in the description or make it more explicit?

Do you want it to be advisory - something I should have read before I replaced the aphiaid in 473 WoRMS (via Arctos) classifications in an attempt to reidentify specimens - or functional - something that prevents me from using inappropriate editors?

https://github.com/ArctosDB/arctos/issues/3121

**Comment by sharpphyl** [comment]
> managed by

> I'm still not seeing any reason for that to exist in the current model.

"Managed by" has more than one meaning.  Sources are managed internally or externally.  I agree that externally managed Sources like WoRMS (via Arctos), do not need "managed by" as a metadata term.  It's obvious they are managed by the external source.

Sometimes, it is helpful with internally managed sources like Arctos, which is still the default for many collections, to know who had a reason to add or modify the name.  If I added it erroneously, I know I can modify or delete it without impacting other collections.  If Teresa added it, I figure she needs it for an identification and I better not mess with it.

Sometimes, the taxon page shows who created the name and when.  If this is always available, it could substitute for the "managed by" metadata.
